{{- if .Values.ingress.basic_auth }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth-secrets-v2
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: base64-encoded-auth
      remoteRef:
        key: {{ .Values.basic_auth.secrets.admin_credentials }}
        property: base64-encoded-auth